name: Coverage

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed

jobs:
  test:
    name: Display coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Run test cases
          run: |
            bundle exec rspec
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
